version: '2'

services:
  nginx:
    build: .
    restart: always
    volumes:
      - ./users:/etc/nginx/users
      - ./nginx.conf /etc/nginx/nginx.conf
      - ./default.conf /etc/nginx/conf.d/default.conf
    ports:
      - 80:80