---
- name: Add repository
  apt_repository:
    repo: "{{item}}"
    state: present
    update_cache: no
  loop:
      - deb https://nginx.org/packages/ubuntu/ jammy nginx
      - deb-src https://nginx.org/packages/ubuntu/ jammy nginx
  tags:
    - nginx

- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: ABF5BD827BD9BF62
  tags:
    - nginx

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    force_apt_get: yes
  tags:
    - nginx

- name: Install Nginx web server
  apt:
    name: nginx
    state: latest
  tags:
    - nginx
  notify:
    - Restart Nginx

###
- name: Update nginx config files
  become: true
  template:
    src: templates/nginx.conf
    dest: "/etc/nginx/nginx.conf"
  tags:
    - nginx
  notify:
    - Restart Nginx

- name: Update nginx default.conf
  become: true
  template:
    src: templates/index.html
    dest: "/usr/share/nginx/html/index.html"
  tags:
    - nginx
  notify:
    - Restart Nginx