---
- name: "Check if apache2-utils is installed"
  package_facts:
    manager: "auto"

- name: "Apache2-utils test result"
  apt:
    name: apache2-utils
    state: latest
  when: "'apache2-utils' not in ansible_facts.packages"
