---
- import_tasks: make_serv.yml
  when: inventory_hostname == "proxy"
  tags:
    - proxy
- import_tasks: 404.yml
  when: inventory_hostname == "proxy"
  tags:
    - 404
- import_tasks: apache2-utils.yml
  when: inventory_hostname == "proxy"
  tags:
    - name
- import_tasks: make_users.yml
  when: inventory_hostname == "proxy"
  tags:
    - name


