---
- name: Inclusion of sites in the proxy
  blockinfile:
    path: /etc/nginx/nginx.conf
    marker: " "
    insertafter: "include"
    block: |
      upstream {{item.url}}_proxy {
        server {{item.ip}}:80;
      }
      server {
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/conf.d/.{{ item.url }}pass;
        server_name {{item.url}};
        location / {
          proxy_pass http://{{item.url}}_proxy;
        }
      }
  loop: "{{ proxy_server }}"

- name: Make file for users
  ansible.builtin.shell:
    chdir: /etc/nginx/conf.d
    cmd: touch .{{url}}pass