---
- name: Register File Stat
  ansible.builtin.stat:
    path: /etc/nginx/conf.d/.{{url}}pass
  register: stat_result


- name: Cat file if exists
  ansible.builtin.shell:
    chdir: /etc/nginx/conf.d
    cmd: htpasswd -b .{{url}}pass {{item.name}} {{item.password}}
  loop: "{{ create_user }}"
  when: stat_result.stat.islnk is defined
  notify:
    - Restart Nginx

- name: File does not exist
  ansible.builtin.shell:
    chdir: /etc/nginx/conf.d
    cmd: echo "File is not found, created...." && .{{url}}pass
  when: stat_result.stat.islnk is not defined
